DROP TABLE BORROWING_RECORD;
DROP TABLE BOOK;
DROP TABLE USERS;
DROP TABLE INVENTORY;

-- 使用者資料表
CREATE TABLE USERS
(
  USER_ID NUMBER NOT NULL,
  PHONE_NUMBER VARCHAR2(50) UNIQUE NOT NULL,
  PASSWORD VARCHAR2(50) NOT NULL,
  USER_NAME VARCHAR2(50) NOT NULL,
  REGISTRATION_TIME DATE NOT NULL,
  LAST_LOGIN DATE,
  CONSTRAINT USERS PRIMARY KEY (USER_ID)  
);

COMMENT ON COLUMN USERS.USER_ID IS '使用者ID';
COMMENT ON COLUMN USERS.PHONE_NUMBER IS '手機';
COMMENT ON COLUMN USERS.PASSWORD IS '密碼';
COMMENT ON COLUMN USERS.USER_NAME IS '使用者名稱';
COMMENT ON COLUMN USERS.REGISTRATION_TIME IS '註冊日期時間';
COMMENT ON COLUMN USERS.LAST_LOGIN IS '最後登入時間';

DROP SEQUENCE USERS_SEQ;
CREATE SEQUENCE USERS_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

-- 庫存資料表
CREATE TABLE INVENTORY
(
  INVENTORY_ID NUMBER NOT NULL,
  ISBN VARCHAR2(50) UNIQUE NOT NULL,
  STORE_TIME DATE NOT NULL,
  STATUS CHAR(1) NOT NULL CHECK (STATUS IN('0','1','2','3','4','5')),
  CONSTRAINT INVENTORY PRIMARY KEY (INVENTORY_ID)  
);

COMMENT ON COLUMN INVENTORY.INVENTORY_ID IS '庫存ID';
COMMENT ON COLUMN INVENTORY.ISBN IS '國際標準書號';
COMMENT ON COLUMN INVENTORY.STORE_TIME IS '書籍入庫購買日期時間';
COMMENT ON COLUMN INVENTORY.STATUS IS '書籍狀態(0:出借中、1:在庫、2:整理中、3:遺失、4:損毀、5:廢棄)';

-- 借閱紀錄資料表
CREATE TABLE BORROWING_RECORD
(
  USER_ID NUMBER NOT NULL,
  INVENTORY_ID NUMBER NOT NULL,
  BORROWING_TIME DATE NOT NULL,
  RETURN_TIME DATE,
  PRIMARY KEY (USER_ID, INVENTORY_ID)
);


COMMENT ON COLUMN BORROWING_RECORD.USER_ID IS '使用者ID';
COMMENT ON COLUMN BORROWING_RECORD.INVENTORY_ID IS '庫存ID';
COMMENT ON COLUMN BORROWING_RECORD.BORROWING_TIME IS '借出日期時間';
COMMENT ON COLUMN BORROWING_RECORD.RETURN_TIME IS '歸還日期時間';

-- 書籍資料表
CREATE TABLE BOOK
(
  ISBN VARCHAR2(50) NOT NULL,
  NAME VARCHAR2(50) NOT NULL,
  AUTHOR VARCHAR2(50) NOT NULL,
  INTRODUCTION VARCHAR2(300) NOT NULL,
  CONSTRAINT BOOK_PK PRIMARY KEY (ISBN),
  CONSTRAINT BOOK_INVENTORY_FK FOREIGN KEY (ISBN) REFERENCES INVENTORY (ISBN)
);

COMMENT ON COLUMN BOOK.ISBN IS '國際標準書號';
COMMENT ON COLUMN BOOK.NAME IS '書名';
COMMENT ON COLUMN BOOK.AUTHOR IS '作者';
COMMENT ON COLUMN BOOK.INTRODUCTION IS '書籍內容簡介';
